version: '3'
services:
  fpm:
    build: ./php
    env_file:
      - .env
    volumes:
    - ./html:/var/www/html:delegated
  apache:
    image: webdevops/apache:alpine-3
    ports:
      - '80:80'
    env_file:
      - .env
    volumes:
      - ./html:/var/www/html:delegated
  db:
    build: ./mysql
    env_file:
      - .env
    ports:
      - '3306'
